---
version: "3.8"

services:
  mysql-container:
    image: mysql:latest
    container_name: sdjpa-hibernate-dao
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - "3307:3306"
    expose:
      - 3307
    environment:
        MYSQL_DATABASE: bookdb
        MYSQL_ROOT_PASSWORD: password
        MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql-data-container:/var/lib/mysql
      - ./mysql-data-container/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sdjpa-hibernate-dao

volumes:
  mysql-data-container:
    driver: local

networks:
  sdjpa-hibernate-dao: