spring:
  datasource:
    url: jdbc:mysql://localhost:3307/bookdb?useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bookadmin
    password: password
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yml
    url: jdbc:mysql://localhost:3307/bookdb?useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    user: bookadmin
    password: password